Rails.application.routes.draw do
  resources :users, :ingredients, :recipes, :recipe_ingredients, :allergens
  # get 'recipes/new'
  # get 'recipes/create'
  # get 'recipes/edit'
  # get 'recipes/update'
  # get 'recipes/destroy'
  # get 'recipes/index'
  # get 'recipes/show'
  # get 'allergens/new'
  # get 'allergens/create'
  # get 'allergens/edit'
  # get 'allergens/update'
  # get 'allergens/destroy'
  # get 'allergens/index'
  # get 'allergens/show'
  # get 'recipe_ingredients/new'
  # get 'recipe_ingredients/create'
  # get 'recipe_ingredients/edit'
  # get 'recipe_ingredients/update'
  # get 'recipe_ingredients/destroy'
  # get 'recipe_ingredients/index'
  # get 'recipe_ingredients/show'
  # get 'ingredients/new'
  # get 'ingredients/create'
  # get 'ingredients/edit'
  # get 'ingredients/update'
  # get 'ingredients/destroy'
  # get 'ingredients/index'
  # get 'ingredients/show'
  # get 'users/new'
  # get 'users/create'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/destroy'
  # get 'users/index'
  # get 'users/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
